pipeline:
  build:
    image: maven:3.5.0-jdk-8-alpine
    commands:
      - mvn -v
      - mvn clean test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

services:
  selenium:
    image: selenium/standalone-chrome