pipeline:
  build:
    image: maven:3.5.0-jdk-8-alpine
    privileged: true
    commands:
      - mvn -v
      - mvn clean test
    volumes:
      - /root/.m2:/root/.m2

services:
  selenium:
    image: selenium/standalone-chrome