pipeline:
  info:
    image: maven:3.5.0-jdk-8-alpine
    commands:
      - mvn -v
  clean:
    image: maven:3.5.0-jdk-8-alpine
    commands:
      - mvn clean
  test:
    image: maven:3.5.0-jdk-8-alpine
    commands:
      - mvn test

services:
  selenium:
    image: selenium/standalone-chrome