pipeline:
  build:
    image: maven:3.5.0-jdk-8-alpine
    commands:
      - ifconfig
      - mvn -v
      - mvn clean test
  volumes:
    - "$HOME/.m2":/root/.m2

services:
  selenium:
    image: selenium/standalone-chrome